### ISSUE TITLE
Add intro text to the about the project page

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#1]
#### Task
Add the intro text in the box below to the **about the project** page.

````
This documentation guide is a Google Africa Developer Scholarship (2021) project made by the [MWS-030 learning phase 1 peer learning group, together with other interested learners and mentors from other peer learning groups](https://github.com/gads-projects/doc/blob/main/contributor.md). Contributions are welcome from any GADS learner or mentor. The project is built to help in the following areas:
````

Write a comment below to get assigned to this task.

**Comment by Blazing-Mike** [comment]
I want to fix this issue

**Comment by Ifycode** [comment]
Assigned to you @Blazing-Mike

**Comment by AJ-Stiles** [comment]
I'd like to fix this issue

**Comment by Ifycode** [comment]
Hi @AJ-Stiles, I've assigned this one to @Blazing-Mike already. Pick another issue to work one. That has not been assigned.

**Comment by Ifycode** [comment]
@Blazing-Mike Having issues sending a pull request? Please follow this process instead:
* Fork the the GADS project gallery doc repo (if you haven't)
* From your fork, [create a new branch](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository) and give it your preferred name
* Edit the page in your fork. Make sure you are in the new branch you created when editing.
* [Send a pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by Ifycode** [comment]
@all-contributors please add @Blazing-Mike for doc

**Comment by Ifycode** [comment]
Issue fixed! Don't bother to comment on this one
