### ISSUE TITLE
Change section title in the contributing guidelines page

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#102]
#### Task

In the contributing guidelines page of the doc, you will find a section with the title: `Editing the project gallery doc` (which is a bit confusing). Change that title to `Editing the documentation`

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by biggietiny** [comment]
Hi @Ifycode I can fix this.

**Comment by Ifycode** [comment]
@biggietiny Thank you for your interest again. I created these two new ones because someone says all tasks are taken but wants to contribute. If by Friday afternoon, no one comes for these, I will then assign it to you.

**Comment by rukundo-kevin** [comment]
@biggietiny I am coming for this too. I think is could try fixing this. @Ifycode

**Comment by Ifycode** [comment]
@rukundo-kevin please go ahead with this task. You are a new contributor. Assigned to you.
