### ISSUE TITLE
Change section title in the video tutorials page

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#103]
#### Task

In the video tutorials page of the doc, you will find a section with the title: `Editing the doc and gallery - video tutorial` (which doesn't look so good). Change that title to `Editing the documentation and gallery`

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by Ifycode** [comment]
Great thank you. Assigned to you! @WNjoroge-glitch

**Comment by WNjoroge-glitch** [comment]
Thank you!
