### ISSUE TITLE
Make correction to the first part of About the project page's intro paragraph

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#110]
#### Task

The first part of the introductory paragraph on the **about the project** page says: "This documentation guide is a Google Africa Developer Scholarship (2021) project made by the MWS-030 learning phase 1 peer learning group, together with other interested learners and mentors from other peer learning groups."

Replace the above with what is in the box below: 

````
The Google Africa Developer Scholarship (GADS) project gallery and documentation project is made by the [MWS-030 learning phase 1 Peer Learning Group \(2021 cohort\), together with interested learners and mentors from other Peer Learning Groups](https://github.com/gads-projects/doc/blob/main/contributor.md).
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by olusanwo** [comment]
I will take this task

**Comment by Ifycode** [comment]
Assigned to you 👍🏽👍🏽👍🏽
