### ISSUE TITLE
Video tutorial: Editing the project gallery doc

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#12]
#### Task

Make a video tutorial following the instruction in [Editing the project gallery doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/contributing) section of the **Contributing guidelines** page. 

* Tutorial must be beginner friendly
* Use the Github web interface, don't use GitHub desktop or command line 
* Use a laptop preferably, not phone
* Audio must be audible
* Do not introduce yourself in the video, instead go straight to the point e.g. start with "Here's how to edit the GADS project gallery doc..."
* Do not show your face, just screen record
* Upload video to YouTube
* Embed the YouTube video on the **video tutorials** page

Write a comment below to get assigned to this task.

**Comment by KeithanPhilander** [comment]
Hey people. This one kinda gives me anxiety since I'm a bit shy but I like this issue and would like to participate so I'll propose a team up. I'm happy to do the post video and audio edits as well as uploading to youtube + embed if someone else is willing to record. :). Let me know.

**Comment by Ifycode** [comment]
Lol... ok @KeithanPhilander Let's hope someone takes up this issue. You'll work together with that person as you have said.

**Comment by KeithanPhilander** [comment]
🤞

**Comment by Ifycode** [comment]
I've assigned myself to this task since no one wants to take it up.

**Comment by KeithanPhilander** [comment]
Hey I'm still willing to do all the post edits.

**Comment by Ifycode** [comment]
😃 @KeithanPhilander ok. There is a problem though. The file size of the videos made with my laptop is very large. Once I upload it to youtube, how will you get it to edit?

**Comment by Ifycode** [comment]
Closing now. Thank you @KeithanPhilander for your wonderful contributions.
