### ISSUE TITLE
Change home page image for doc

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#14]
#### Task
![google-africa-developer-scholarship-gads-program-2020-1 (1)](https://user-images.githubusercontent.com/45185388/129614295-2abfb3fb-11d5-4255-bec6-c6abc5c60c13.png)

We're currently using the above image on the docs homepage. We want to change it to something unique.  The design doesn't have to be complex but must look nice. 

Should have same slim rectangular shape, we don't want the image too big on the page.

Remove the previous image and add the new one on the homepage.

Write a comment below to get assigned to this task.

**Comment by KeithanPhilander** [comment]
Hi there! I would like to contribute to this task.

**Comment by Ifycode** [comment]
Yay! Welcome @KeithanPhilander Looks like you are into design too... interesting. Assigned to you!

**Comment by Ifycode** [comment]
@all-contributors add @KeithanPhilander for doc

**Comment by Ifycode** [comment]
Nice work @KeithanPhilander When you are adding the image, can you place it under that header and before the introductory text? It looks nicer on the gitbook doc that way.

<img width="807" alt="Screenshot 2021-08-19 at 6 02 07 AM" src="https://user-images.githubusercontent.com/45185388/130011442-9cfc6650-b2d6-4d84-83d1-cfe600732214.png">

**Comment by Ifycode** [comment]
Issue fixed! Don't bother to comment on this one
