### ISSUE TITLE
Link text on home page to the contributing guidelines page

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#21]
#### Task
Look for this sentence on the home page:
"Adding your project here is optional, but adding your project is **one of the many ways** you become a contributor to the GADS project gallery doc"

Turn (only the) bold text in the above sentence to link that takes user to the contributing guidelines page. Replace it with what is in the the box below: 
````
[one of the many ways](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/contributing)
````

Write a comment below to get assigned to this task.

**Comment by kaylezy** [comment]
I would like to contribute on this page

**Comment by Ifycode** [comment]
Great! Assigned to you! @kaylezy

**Comment by Ifycode** [comment]
@all-contributors add @kaylezy for doc

**Comment by Ifycode** [comment]
Issue fixed! Don't bother to comment on this one
