### ISSUE TITLE
Add this short note to the about the project page 

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#3]
#### Task
Add the intro text in the box below to the bottom of the **about the project** page.

````
**Note:** If you choose to add your projects to the project gallery, you will only be added as one of the [contributors to the project doc](https://github.com/gads-projects/doc/blob/main/contributor.md). The GADS team will not come to the gallery to check your project. Please submit your projects as instructed by the GADS team first, before you come here to add your projects. Reach out to any of the program assistants or mentors incase you have questions.
````

Write a comment below to get assigned to this task.

**Comment by Blazing-Mike** [comment]
i want to fix this issue

**Comment by Ifycode** [comment]
Alright @Blazing-Mike, a different branch and PR for this one.

**Comment by Ifycode** [comment]
Looks like there will be more contributors. Let's do it this way @Blazing-Mike. Send a PR for the issue I assigned you to 👉🏾 #1 

 I can then reassign you once you you are done with that (if no one takes up this issue).

**Comment by Ifycode** [comment]
You can now go ahead to submit a PR for this one @Blazing-Mike 
Assigned to you!

**Comment by Ifycode** [comment]
Issue fixed! Don't bother to comment on this one
