### ISSUE TITLE
Replace sentence in homepage's introductory paragraph

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#45]
#### Task
"Adding your project here is optional, but adding your project is one of the many ways you become a contributor to the GADS project gallery doc". 

Look for the above sentence in the homepage's introductory paragraph and replace it with what is in the box below: 

````
Adding your GADS projects to the project gallery is [one of the many ways](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/contributing) you become a [contributor](https://github.com/gads-projects/doc/blob/main/contributor.md) to the GADS project gallery doc. The sections below contain information about GADS projects.
````

Write a comment below to get assigned to this task.

**Comment by kaylezy** [comment]
available for this, please

**Comment by Ifycode** [comment]
Assigned to you @kaylezy
