### ISSUE TITLE
Link project gallery text to project gallery repo in about the project page

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#46]
#### Task
In the **About the project page**, the first list item says: 

"Create a **project gallery** where learners can display projects made during GADS program."

Link the text "project gallery" to the project gallery repo with what is in the box below:
````
[project gallery](https://github.com/gads-projects/gallery)
````

Write a comment below to get assigned to this task.

**Comment by Blazing-Mike** [comment]
Assign me to this task

**Comment by Ifycode** [comment]
Assigned to you @Blazing-Mike

**Comment by Ifycode** [comment]
@Blazing-Mike you didn't do what was written in the task. I mistakenly merged it, but I've reset it. You are supposed to replace the words "project gallery" in that list item with that link, not write the link on a new line.
Please read the task again and do it well this time. Thanks.
