### ISSUE TITLE
Replace text in editing the project gallery doc section

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#47]
#### Task
"On the Gitbook doc, click on the the edit on Github button at the top right corner of a page to take you directly to the page to edit on Github".

The text above is found in the **contributing guidelines** page under the **Editing the project gallery doc** title. Replace it with what is in the box below:
````
You can locate the file you want to edit in the [doc repo](https://github.com/gads-projects/doc) by manually searching for the file in the doc repo or via the edit on Github button on the [Gitbook doc](https://obiagba-mary.gitbook.io/gads-projects). Go to a particular page on the Gitbook doc, then click on the edit on Github button (or github icon in the case of smaller devices) to take you to the exact file to edit. Follow these steps to edit the file since you cannot directly make changes to the repo:
````

Write a comment below to get assigned to this task.

**Comment by KeithanPhilander** [comment]
Could you assign this one to me?

**Comment by Ifycode** [comment]
Hey, i left a [comment for you on the PR](https://github.com/gads-projects/doc/pull/49#issuecomment-903098278).

**Comment by Ifycode** [comment]
Nice work on the last PR. Assigned to you! @KeithanPhilander
