### ISSUE TITLE
Add contributions welcome badge to contributing guidelines page

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#48]
#### Task
Add the contributions welcome badge in the box below to the **contributing guidelines** page. Add it directly under the **contributing guidelines** title, before the introductory paragraph. It must be on its on line.

````
![contributions welcome](https://img.shields.io/badge/contributions-welcome-brightgreen.svg?style=flat)
````

Write a comment below to get assigned to this task.

**Comment by KeithanPhilander** [comment]
I could do this.

**Comment by Ifycode** [comment]
Cool! Welcome back. Assigned to you! @KeithanPhilander 😃
