### ISSUE TITLE
Add table with image in the individual-2021.md file in the gallery repo

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#63]
#### Task
Go to the [gallery repo](https://github.com/gads-projects/gallery), add the table in the box below to the **individual-2021.md** file. Add it just after the **Individual projects** header.

````
<table>
  <tr>
    <td align="center"><a href="add-link-here"><img src="https://user-images.githubusercontent.com/45185388/130367237-173da632-2f98-4fd0-9eb4-4ea28cda9b81.png?v=4?s=100" width="300px;" alt="add-alt-text"/><br /><sub><b>Add your GADS project</b></sub></a><br /></td>
   </tr>
</table>
````

Task for @k-man-null

**Comment by k-man-null** [comment]
Lets do this...

**Comment by Ifycode** [comment]
Assigned to you ! 👍🏽

**Comment by Ifycode** [comment]
@all-contributors add @k-man-null as a contributor for doc.
