### ISSUE TITLE
Replace part of sentence with links in contributor.md file

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#68]
#### Task
In the contributor.md file, look for this sentence: "Thanks to these wonderful people for improving the GADS project gallery and documentation".

Replace the "project gallery and documentation" part with what is in the box below:
````
[project gallery](https://github.com/gads-projects/gallery) and [documentation](https://obiagba-mary.gitbook.io/gads-projects)
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by KeithanPhilander** [comment]
I could do this one.

**Comment by Ifycode** [comment]
Hey @KeithanPhilander Let's cook up more tasking task for you instead 😉 and leave this type of tasks for new intakes.

**Comment by Ifycode** [comment]
Assigned to you @KeithanPhilander
