### ISSUE TITLE
Make list item 4 more explanatory - in Ways you can contribute to the project section

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#74]
#### Task

Go to the contributing guidelines page. Under the subheading **Ways you can contribute to the project**, check for the list item that says: "Suggest and/or add content, sections or page to the GADS project gallery doc".

Replace it with what is in the box below: 

````
* [Create an issue](https://github.com/gads-projects/doc/issues) to suggest and/or add content, sections, files or page to the doc repo or the gallery repo
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by simplyenny** [comment]
i'd like to attempt this

**Comment by Ifycode** [comment]
Assigned to you! @simplyenny

**Comment by Ifycode** [comment]
Hi @simplyenny Thank you for asking to work on this task. I will be unassigning you from this task by the end of tomorrow (saturday), if you do not submit a PR by then. Just wanted to type it here, incase you receive this as notification.

**Comment by simplyenny** [comment]
on it already. this week has been a rollacoaster ride for me.
