### ISSUE TITLE
Make list item 5 more explanatory - in Ways you can contribute to the project section

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#75]
#### Task

Go to the contributing guidelines page. Under the subheading **Ways you can contribute to the project**, check for the list item that says: "Report and fix broken links, grammatical or typographical errors in either the GADS project gallery doc or the project gallery repo".

Replace it with what is in the box below: 

````
* [Create an issue](https://github.com/gads-projects/doc/issues) to report and fix problems such as broken links, grammatical or typographical errors present in the doc repo or the gallery repo
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by biggietiny** [comment]
Hi @Ifycode i can take this on.

**Comment by Ifycode** [comment]
@biggietiny 👍🏽👍🏽👍🏽 Assigned to you 😃
