### ISSUE TITLE
Make list item 3 more understandable - in Ways you can contribute to the project section

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#76]
#### Task

Go to the contributing guidelines page. Under the subheading **Ways you can contribute to the project**, check for the list item that says: "Update outdated information in the GADS project gallery doc".

Replace it with what is in the box below: 

````
* Update outdated information in the [doc repo](https://github.com/gads-projects/doc) or [gallery repo](https://github.com/gads-projects/gallery)
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by AfiaAniebiet** [comment]
I can take this.

**Comment by Ifycode** [comment]
Yes please @AfiaAniebiet Assigned to you 😃👍🏽

**Comment by Ifycode** [comment]
Hi @AfiaAniebiet Thank you for asking to work on this task. I will be unassigning you from this task by the end of tomorrow (saturday), if you do not submit a PR by then. Just wanted to type it here, incase you receive this as notification.

**Comment by KimaniKen** [comment]
Hello Let me take this

**Comment by Ifycode** [comment]
Alright. Reassigned to you @KimaniKen

**Comment by Ifycode** [comment]
Hi @KimaniKen Thank you for asking to work on this task. This ought to have been relaesed in the bug fix. I will be unassigning you from this task by the end of tomorrow (saturday), if you do not submit a PR by then. Just wanted to type it here, incase you receive this as notification.
