### ISSUE TITLE
Make list item 1 more understandable - in Ways you can contribute to the project section

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#77]
#### Task

Go to the contributing guidelines page. Under the subheading **Ways you can contribute to the project**, check for the list item that says: "Add your GADS projects to the project gallery repo".

Replace it with what is in the box below: 

````
* Add your GADS projects to the [gallery repo](https://github.com/gads-projects/gallery)
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by BakungaBronson** [comment]
@Ifycode , I can take this on

**Comment by Ifycode** [comment]
You want to finish all the issues before others come 😂 Please check back here on Thursday if you have time. If no one takes it up then i'll assign it to you.

**Comment by BakungaBronson** [comment]
![image](https://user-images.githubusercontent.com/51344005/131302700-4fc1fa8c-279d-41c3-b309-c291f6e670de.png)
A bit confused as to if this was already completed though, the difference is the about 2 words. Please advise 👀

**Comment by BakungaBronson** [comment]
> You want to finish all the issues before others come 😂 Please check back here on Thursday if you have time. If no one takes it up then i'll assign it to you.

My bad 😂🙌, I'll come back on Thursday then.

**Comment by Ifycode** [comment]
Alright. Thank you!

**Comment by Olaoluwadunni** [comment]
@Ifycode I will take this up

**Comment by Ifycode** [comment]
Ok! @Olaoluwadunni Assigned to you! 😃👍🏽
