### ISSUE TITLE
Fix 1st list item in Adding your project to the gallery section

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#78]
#### Task

Go to the contributing guidelines page. Under the subheading **Adding your project to the gallery**, check for the list item that says: "Fork the the project gallery repo (if you haven't)".

Replace it with what is in the box below: 

````
* Fork the [gallery repo](https://github.com/gads-projects/gallery) \(if you haven't\)
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by BakungaBronson** [comment]
@Ifycode , I can take this on.

**Comment by Ifycode** [comment]
Assigned to you @BakungaBronson 😃👍🏽
