### ISSUE TITLE
Fix 2 statements in introductory paragraph on the contributing guidelines page

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#79]
#### Task

Go to the contributing guidelines page and make these two changes in the introductory paragraph:

Look for this sentence "Thank you for your interest to contribute to the GADS project gallery doc". Replace it with what is in the box below: 

````
Thank you for your interest to contribute to the GADS project gallery and documentation project.
````

Also look for this sentence "Make sure to submit your projects as instructed by the GADS team or your mentors, before coming to add your project here". Replace it with what is in the box below: 

````
Make sure to submit your project(s) as instructed by the GADS team or your mentors, before coming to add your project(s) to the project gallery.
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by Qudusayo** [comment]
Available to complete the task!

**Comment by Ifycode** [comment]
Assigned to you! @Qudusayo 👍🏽 Go ahead please.
