### ISSUE TITLE
Update Editing the project gallery doc section with video tutorial link

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#80]
#### Task

Go to the contributing guidelines page. Under the subheading **Editing the project gallery doc**, look for this sentence "Follow these steps to edit the file since you cannot directly make changes to the repo:".

Replace it with what is in the box below: 

````
[Watch video tutorial](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) or follow these steps to edit the file since you cannot directly make changes to the repo:
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by akintoluvic** [comment]
Hey @Ifycode, I will like to take up this task

**Comment by akintoluvic** [comment]
Thanks @Ifycode, I should create a branch, make changes and then send a PR right?

**Comment by Ifycode** [comment]
Yes. Go ahead.

**Comment by akintoluvic** [comment]
Here is the PR for the fix https://github.com/gads-projects/doc/pull/100 @Ifycode

**Comment by Ifycode** [comment]
Merged. Nice work. Thank you for your contribution.
