### ISSUE TITLE
Update project name in the doc homepage's introductory paragraph

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#82]
#### Task

Go to the doc homepage (i.e. the readme.md file). In the introductory paragraph which is directly under the image, look for this sentence: "Adding your GADS projects to the project gallery is one of the many ways you become a contributor to the GADS project gallery doc".

Replace the last part of the sentence "GADS project gallery doc" with: `GADS project gallery and documentation project`.

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by Zaid837** [comment]
Hi, would like to close this out.

**Comment by Ifycode** [comment]
Thank you 😌 Assigned to you @Zaid837 👍🏽
