### ISSUE TITLE
Update Adding your project to the gallery section with video tutorial link

### ISSUE THREAD

**Issue by Ifycode** [gads-projects/doc#85]
#### Task

Go to the contributing guidelines page. Under the subheading **Adding your project to the gallery**, look for this sentence "Follow these steps to add your projects:".

Replace it with what is in the box below: 

````
[Watch video tutorial](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) or follow these steps to add your projects to the gallery:
````

**Please do these:**
- Write a comment below to get assigned to this task.
- Watch [video tutorial from the doc](https://obiagba-mary.gitbook.io/gads-projects/contribution-guide/video-tutorials) to see how to go about editing files and submitting pull request.

**Comment by Ismail-Opatola** [comment]
Hi, would like to complete this task

**Comment by Ifycode** [comment]
Cool! Assigned to you @Ismail-Opatola 👍🏽
